version: "2.1"

services :
    nginx:
        build: ./nginx/
        ports:
            - 80:80
        links:
            - php
        volumes:
            - ./site/html:/var/www/html
     
    php:
        image: php:7.0-fpm
        expose:
            - 9000
        volumes:
            - ./site/html:/var/www/html
            
